### ISSUE TITLE
Assignment not working 

### ISSUE THREAD

**Issue by madeleineeh** [steren/secret-santa#4]
Hi,
unfortunately assignment doesn't work. Always get this error message:

![image](https://user-images.githubusercontent.com/72437137/95175574-f7a50d00-07bb-11eb-99f5-58362a755150.png)

Tried variuos test rounds with 3 to 5 members, always using valid email adresses, entering groups or not. Number of presents to  offer should be "1", but it doen't work.

Except when I set "number of presents to offer" to "2". But that isn't wanted...

Do you have any idea or support on that? 

Best,
Madeleine

**Comment by steren** [comment]
It would be helpful if you could share an example spreadsheet that reproduces the error.

Please re-open when you've done so
